package com.veyra.app

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale

class VeyraStore(private val context: Context) {
    private val prefs = context.getSharedPreferences("veyra_store", Context.MODE_PRIVATE)
    data class HabitRecord(val id: Long, val name: String)
    data class Achievement(val id: String, val title: String, val description: String, val unlocked: Boolean)
    private fun today(): String = SimpleDateFormat("yyyy-MM-dd", Locale.US).format(Date())
    private fun dateFormat(): SimpleDateFormat = SimpleDateFormat("yyyy-MM-dd", Locale.US).apply { isLenient = false }
    private fun isValidDate(value: String): Boolean = runCatching { dateFormat().parse(value)?.let { dateFormat().format(it) == value } == true }.getOrDefault(false)
    fun userName(): String = prefs.getString("user_name", "")?.trim().orEmpty()
    fun setUserName(value: String) { prefs.edit().putString("user_name", value.trim().take(40)).apply() }
    fun habits(): List<HabitRecord> { val raw=prefs.getString("habits",null);if(raw==null||raw=="[]"){val d=listOf(HabitRecord(1,"Drink water"),HabitRecord(2,"Study 20 min"),HabitRecord(3,"Move 20 min"));if(raw==null)setHabits(d);return if(raw=="[]")emptyList()else d};val j=JSONArray(raw);return List(j.length()){i->val o=j.getJSONObject(i);HabitRecord(o.getLong("id"),o.getString("name"))} }
    fun setHabits(items:List<HabitRecord>){val j=JSONArray();items.forEach{j.put(JSONObject().put("id",it.id).put("name",it.name))};prefs.edit().putString("habits",j.toString()).apply()}
    fun renameHabit(id:Long,name:String){val n=name.trim();if(n.isBlank())return;setHabits(habits().map{if(it.id==id)HabitRecord(id,n)else it})}
    fun removeHabit(id:Long){setHabits(habits().filterNot{it.id==id});val e=prefs.edit();val f=dateFormat();val c=Calendar.getInstance();repeat(3650){e.remove("done_${f.format(c.time)}_$id");c.add(Calendar.DAY_OF_YEAR,-1)};e.apply()}
    fun isCompleted(id:Long,date:String=today())=prefs.getBoolean("done_${date}_$id",false)
    fun setCompleted(id:Long,done:Boolean,date:String=today())=prefs.edit().putBoolean("done_${date}_$id",done).apply()
    fun completionDates(id:Long,days:Int):List<String>{val r=mutableListOf<String>();val f=dateFormat();val c=Calendar.getInstance();repeat(days.coerceAtLeast(0)){r+=f.format(c.time);c.add(Calendar.DAY_OF_YEAR,-1)};return r.filter{isCompleted(id,it)}}
    fun streak(ids:List<Long>):Int{if(ids.isEmpty())return 0;val c=Calendar.getInstance();val f=dateFormat();var n=0;while(ids.all{isCompleted(it,f.format(c.time))}){n++;c.add(Calendar.DAY_OF_YEAR,-1)};return n}
    fun bestStreak(ids:List<Long>,days:Int=365):Int{if(ids.isEmpty()||days<=0)return 0;val f=dateFormat();val c=Calendar.getInstance();var best=0;var current=0;repeat(days){if(ids.all{isCompleted(it,f.format(c.time))}){current++;best=maxOf(best,current)}else current=0;c.add(Calendar.DAY_OF_YEAR,-1)};return best}
    fun completedCount(days:Int,ids:List<Long>):Int{if(ids.isEmpty())return 0;val f=dateFormat();val c=Calendar.getInstance();var n=0;repeat(days.coerceAtLeast(0)){val d=f.format(c.time);n+=ids.count{isCompleted(it,d)};c.add(Calendar.DAY_OF_YEAR,-1)};return n}
    fun mood()=prefs.getInt("mood",2).coerceIn(0,3);fun setMood(v:Int)=prefs.edit().putInt("mood",v.coerceIn(0,3)).apply();fun xp()=prefs.getInt("xp",0).coerceAtLeast(0);fun setXp(v:Int)=prefs.edit().putInt("xp",v.coerceAtLeast(0)).apply();fun goal()=prefs.getString("goal","Build a better day")?:"Build a better day";fun setGoal(v:String)=prefs.edit().putString("goal",v.trim().ifBlank{"Build a better day"}).apply();fun journal(date:String=today())=prefs.getString("journal_$date","")?:"";fun setJournal(v:String,date:String=today())=prefs.edit().putString("journal_$date",v).apply();fun achievement(id:String)=prefs.getBoolean("achievement_$id",false);fun unlockAchievement(id:String):Boolean{if(achievement(id))return false;prefs.edit().putBoolean("achievement_$id",true).apply();return true}
    fun achievements():List<Achievement>{val d=listOf(Triple("first_step","First Step","Complete your first habit."),Triple("week_warrior","Week Warrior","Reach a 7-day streak."),Triple("century","Century","Earn 100 XP."),Triple("journalist","Thoughtful","Write your first journal entry."));return d.map{Achievement(it.first,it.second,it.third,achievement(it.first))}}
    fun exportJson():String{val root=JSONObject().put("schema",1).put("userName",userName()).put("goal",goal()).put("mood",mood()).put("xp",xp());val hs=JSONArray();habits().forEach{hs.put(JSONObject().put("id",it.id).put("name",it.name))};root.put("habits",hs);val ids=habits().map{it.id};val f=dateFormat();val c=Calendar.getInstance();val done=JSONArray();repeat(3650){val d=f.format(c.time);ids.filter{isCompleted(it,d)}.forEach{done.put(JSONObject().put("date",d).put("habitId",it))};c.add(Calendar.DAY_OF_YEAR,-1)};root.put("completed",done);val journals=JSONArray();val j=Calendar.getInstance();repeat(3650){val d=f.format(j.time);val body=journal(d);if(body.isNotBlank())journals.put(JSONObject().put("date",d).put("body",body));j.add(Calendar.DAY_OF_YEAR,-1)};root.put("journals",journals);val a=JSONArray();achievements().filter{it.unlocked}.forEach{a.put(it.id)};root.put("achievements",a);val nudges=JSONArray();NudgeStore(context).all().forEach{nudges.put(it.toJson())};root.put("nudges",nudges);val reminders=JSONArray();HabitReminderStore(context).all().forEach{reminders.put(JSONObject().put("habitId",it.habitId).put("habitName",it.habitName).put("hour",it.hour).put("minute",it.minute).put("enabled",it.enabled))};root.put("habitReminders",reminders);return root.toString(2)}
    fun importJson(raw:String){val root=try{JSONObject(raw)}catch(_:Exception){throw IllegalArgumentException("Backup is not valid JSON")};if(root.optInt("schema",0)!=1)throw IllegalArgumentException("Unsupported backup version");val imported=root.optJSONArray("habits")?:throw IllegalArgumentException("Backup is missing habits");val validated=JSONArray();val ids=mutableSetOf<Long>();for(i in 0 until imported.length()){val o=imported.optJSONObject(i)?:throw IllegalArgumentException("Invalid habit data");val id=o.optLong("id",-1);val name=o.optString("name","").trim();if(id<1||name.isBlank()||!ids.add(id))throw IllegalArgumentException("Invalid habit data");validated.put(JSONObject().put("id",id).put("name",name))};val validA=achievements().map{it.id}.toSet();val oldReminders=HabitReminderStore(context).all();oldReminders.forEach{HabitReminderScheduler.cancel(context,it.habitId)};context.getSharedPreferences("veyra_habit_reminders",Context.MODE_PRIVATE).edit().clear().apply();val nudgeStore=NudgeStore(context);nudgeStore.clear();val e=prefs.edit().clear();e.putString("habits",validated.toString()).putString("user_name",root.optString("userName","").trim().take(40)).putString("goal",root.optString("goal","Build a better day")).putInt("mood",root.optInt("mood",2).coerceIn(0,3)).putInt("xp",root.optInt("xp",0).coerceAtLeast(0));root.optJSONArray("completed")?.let{for(i in 0 until it.length()){val o=it.optJSONObject(i)?:throw IllegalArgumentException("Invalid completion data");val date=o.optString("date","");val id=o.optLong("habitId",-1);if(!isValidDate(date)||id !in ids)throw IllegalArgumentException("Invalid completion data");e.putBoolean("done_${date}_$id",true)}};root.optJSONArray("journals")?.let{for(i in 0 until it.length()){val o=it.optJSONObject(i)?:throw IllegalArgumentException("Invalid journal data");val date=o.optString("date","");if(!isValidDate(date))throw IllegalArgumentException("Invalid journal data");e.putString("journal_$date",o.optString("body"))}};root.optJSONArray("achievements")?.let{for(i in 0 until it.length()){val id=it.optString(i,"");if(id !in validA)throw IllegalArgumentException("Invalid achievement data");e.putBoolean("achievement_$id",true)}};e.apply();root.optJSONArray("nudges")?.let{for(i in 0 until it.length()){val o=it.optJSONObject(i)?:continue;val n=Nudge(o.optLong("id"),o.optString("name"),o.optInt("interval",60),o.optInt("start",8),o.optInt("end",22),o.optBoolean("enabled",true));nudgeStore.save(n)}};root.optJSONArray("habitReminders")?.let{for(i in 0 until it.length()){val o=it.optJSONObject(i)?:continue;val id=o.optLong("habitId",-1);val name=o.optString("habitName","").trim();val hour=o.optInt("hour",0);val minute=o.optInt("minute",0);val enabled=o.optBoolean("enabled",false);if(id !in ids||name.isBlank()||hour !in 0..23||minute !in 0..59)throw IllegalArgumentException("Invalid habit reminder data");HabitReminderStore(context).save(HabitReminder(id,name,hour,minute,enabled))}}}
    fun reset(){prefs.edit().clear().apply()}
}
